# TP Erreur inverse

## Erreur inverse - Cas symétrique

Soient $A\in \mathcal{S}_n(\mathbb{R})$ inversible, $b\in\mathbb{R}^n$ et $x\in\mathbb{R}^n$ solution de $$Ax=b.$$

On dispose d'un algorithme permettant la résolution numérique d'un tel problème. L'exécution de celui-ci conduit à une solution numérique $\tilde{x}$, entachée d'erreurs : $$A\tilde{x}\neq b. $$

L'erreur inverse de cet algorithme, en norme de Frobenius, peut être obtenue depuis la solution du problème d'optimisation suivant : $$\min_{\Delta \in \mathcal{C}} \Vert \Delta \Vert^2_F,$$

avec $$\mathcal{C}=\left\{ \Delta \in \mathcal{S}_n(\mathbb{R}) \mbox{ t.q. } (A+\Delta)\tilde{x}=b\right\}.$$

On s'intéresse à un problème plus simple qui consiste à chercher un élément de $\mathcal{C}$, si ce dernier n'est pas vide :

$$(\mathcal{E})\quad \mbox{ Trouver }\Delta \in \mathcal{S}_n(\mathbb{R}) \mbox{ t.q. } (A+\Delta)\tilde{x}=b.$$

En écrivant $$\mathcal{C}=\mathcal{C}_1\bigcap\mathcal{C}_2,$$ avec $$\mathcal{C}_1=\mathcal{S}_n(\mathbb{R}), \quad \mathcal{C}_2=\left\{\Delta \in \mathcal{M}_n(\mathbb{R}) \mbox{ t.q. } (A+\Delta)\tilde{x}=b\right\},$$ on est amenés à chercher un élément sur l'intersection de deux convexes fermés non vides.

**Question 1 :** Justifier que ces deux parties sont convexes, fermées et non vides.


### Réponse

Soient $\Delta_1,\,\Delta_2\in\mathcal{C}_1$ et $\lambda\in[0,1]$, alors $\left(\lambda\Delta_1 + (1-\lambda)\Delta_2\right)_{ij} = (\lambda\Delta_1)_{ij} + ((1-\lambda)\Delta_1)_{ij} = (\lambda\Delta_1)_{jj} + ((1-\lambda)\Delta_1)_{ji} = \left(\lambda\Delta_1 + (1-\lambda)\Delta_2\right)_{ji}$ donc $\lambda\Delta_1 + (1-\lambda)\Delta_2 \in \mathcal{C}_1$ donc $\mathcal{C}_1$ convexe. De plus l'application $\Delta \mapsto \Delta - \Delta^T$ définie sur $\mathcal{M}_n(\mathbb{R})$ est linéaire en dimension finie donc continue donc $f^{-1}(\{0\}) = \mathcal{S}_n(\mathbb{R}) = \mathcal{C}_1$ est fermé. Enfin $\mathcal{C}_1$ non vide car $0$ est dedans.

De même, $\mathcal{C}_2$ convexe, fermé comme image réciproque de $\{0\}$ par une application continue, et non vide par hypothèse.

On définit pour cela le problème d'optimisation suivant : 
$$(\mathcal{P})\quad \min_{\Delta \in \mathcal{M}_n(\mathbb{R})} f(\Delta)=\max(d(\Delta,\mathcal{C}_1),d(\Delta,\mathcal{C}_2))$$

avec $d(\Delta,\mathcal{C}_i)$ la distance de $\Delta$ à $\mathcal{C}_i$.

**Question 2 :** On choisit de munir $\mathcal{M}_n(\mathbb{R})$ du produit scalaire $<X,Y>=tr(XY^T)$. On a alors $d(\Delta,\mathcal{C}_i)=\Vert \Delta - \Pi_{\mathcal{C}_i}(\Delta)\Vert_F$, avec $\Vert \Vert_F$ la norme de Frobenius, et $\Pi_{\mathcal{C}_i}(\Delta)$ le projeté de $\Delta$ sur $\mathcal{C}_i$. Donner l'expression analytique des $\Pi_{\mathcal{C}_i}(\Delta)$.

$\Pi_{\mathcal{C}_1}(\Delta) = \displaystyle\frac{\Delta + \Delta^T}{2}$. 
$$\begin{align}
\Pi_{\mathcal{C}_2}(\Delta) &= \underset{X\in\mathcal{C}_2}{\operatorname{argmin}} \frac 1 2 \Vert X-\Delta\Vert_F^2 \\
&= \underset{X\tilde{x}=b-A\tilde{x}}{\underset{X\in\mathcal{M}_n(\mathbb{R})}{\operatorname{argmin}}} \frac 1 2 \Vert X-\Delta\Vert_F^2
\end{align}
$$

On pose $f_2(X) = \frac 1 2 \Vert X-\Delta\Vert_F^2$ et $h(X) = X\tilde{x}=b-A\tilde{x}$.

f est continue. L'ensemble des contraintes n'est pas forcément bornée mais f est clairement coercive => CS1 => existence d'un minimum.

KKT ?
- $f_2$, $h$ sont $C^1$
- (HQC) vérifier que la famille $(\nabla h_i(X))$ est libre, $i=1,...,n$

$$
\mathcal{L}(X,\,\lambda) = f_2(X)+ \lambda^Th(X)
$$

KKT => $\exists \lambda$ tq $\nabla\mathcal{L}(X, \lambda)=0$.

On trouve donc :
$$
\lambda = \displaystyle\frac{1}{\Vert\tilde{x}\Vert_2^2} \left[\Delta\tilde{x}-(b-A\tilde{x})\right] \in\mathbb{R}^n
$$
$$
X=\Delta\left(I_n - \displaystyle\frac{\tilde{x}\tilde{x}^T}{\Vert\tilde{x}\Vert_2^2}\right)+\displaystyle\frac{(b-A\tilde{x})\tilde{x}^T}{\Vert\tilde{x}\Vert_2^2}
$$
donc
$$
\Pi_{\mathcal{C}_2}(\Delta)=\Delta\left(I_n - \displaystyle\frac{\tilde{x}\tilde{x}^T}{\Vert\tilde{x}\Vert_2^2}\right)+\displaystyle\frac{(b-A\tilde{x})\tilde{x}^T}{\Vert\tilde{x}\Vert_2^2}
$$

Remarque : $\lambda^T(X\tilde{x})=tr(\lambda^T(X\tilde{x}))$. Ce qui nous permet d'obtenir.

$$ \mathcal{L}(x,\,\lambda) = \frac 1 2 \left<X-\Delta, X-\Delta\right>+\left<X, \lambda \tilde{x}\right>$$

$$\nabla_X \mathcal{L}(x,\,\lambda)=X-\Delta+\lambda\tilde{x}^T$$

**Question 3 :** Proposer un sous-gradient de $f$ en $\Delta$, $\forall \Delta \in \mathcal{C}$.



**Qestion 4 :** Résoudre le problème $ (\mathcal{P})$ par l'algorithme du sous-gradient.

In [1]:
using LinearAlgebra

In [2]:
n = 100;
A = Symmetric(randn(n,n));
x = randn(n);
x_tilde = x + 1e-2*rand(n)
b = A*x

100-element Array{Float64,1}:
  -4.452449834753848
  18.974513463599465
  13.99628970976913
  -2.2116520867573186
   9.30141959561169
  12.20145299618718
  -0.6806388665879703
  -5.6574844928796875
   7.3287985336070225
   0.9892347126469376
   3.321625071053113
 -12.909823810767577
 -12.731902677739084
   ⋮
   5.569602165167632
   6.949407727230475
   8.52334286180428
   3.585093789536587
   0.02337904649955691
   1.9260581040494453
  -5.519347253400442
  -5.696798814924229
   2.7557234949715843
   8.046392628840103
   7.6713302201421065
  11.02855742238813

In [3]:
function pi1(Delta)
    return (Delta+transpose(Delta))/2;
end
    
function pi2(Delta, b, x_tilde)
    tx_tilde = transpose(x_tilde);
    norme = norm(x_tilde, 2);
    return Delta-Delta*x_tilde*tx_tilde/norme^2+(b-A*x_tilde)*tx_tilde/norme^2;
end

function evalf(Delta, b, x_tilde)
    d1 = norm(Delta-pi1(Delta)); # with p=2, for a matrix, computes Frobenius norm
    d2 = norm(Delta-pi2(Delta,b,x_tilde));
    return max(d1,d2);
end

# Return one subgradient of f at Delta
function subgradf(Delta, b, x_tilde)
    eval1 = Delta-pi1(Delta);
    eval2 = Delta-pi2(Delta,b,x_tilde);
    d1 = norm(eval1);
    d2 = norm(eval2);
    
    if(max(d1,d2)==d1)
        g = eval1/d1;
    else
        g = eval2/d2;
    end
       
    return g;
end

subgradf (generic function with 1 method)

In [4]:
#Pkg.add("Plots")
using Plots

# Initialisation
Delta = zeros(n,n);
Delta_best = Delta;
i = 0;
fbest = 1000000;
histo_subgradient_simple =[];

lambda=1e-2;

pas=4;
itermax_subgradient_simple=50;

Delta_k = Delta;
while i < itermax_subgradient_simple
    i = i + 1;
    gk = subgradf(Delta_k, b, x_tilde);
    #print(norm(gk,2),"\n")
    
    if pas == 1
        Delta_k -= 1e-2*gk;
    elseif pas == 2
        Delta_k -= 1/(100i) * gk;
    elseif pas == 3
        Delta_k -= 1/(norm(gk,2)*sqrt(i)) * gk;
    elseif pas == 4
        #print(evalf(Delta_k, b, x_tilde),"\n")
        Delta_k -= evalf(Delta_k, b, x_tilde)/norm(gk,2)^2 * gk;
    end
    
    if evalf(Delta_k, b, x_tilde) < fbest
        #print("hi!\n")
        fbest = evalf(Delta_k, b, x_tilde);
        Delta_best = Delta_k;
    end
    
    append!(histo_subgradient_simple, fbest);
end

plotly();

iter_subgradient_simple=1:itermax_subgradient_simple;

┌ Info: For saving to png with the Plotly backend ORCA has to be installed.
└ @ Plots /home/hoellinger/.julia/packages/Plots/4EfKl/src/backends.jl:373


In [5]:
plot(iter_subgradient_simple,histo_subgradient_simple,title="Convergence curve",label=["f"],lw=3,ann=[(55,80,"Sous-gradient simple")])

<!DOCTYPE html>
 
 
 Plots.jl

Vérification :

In [6]:
Delta_best == transpose(Delta_best)

true

In [7]:
isapprox(pi2(Delta_best, b, x_tilde), Delta_best; atol=1e-8)

true

OK !

## Autre application

Objectif : complétion d'une matrice $A\in\mathcal{S}_n^+(\mathbb{R})$ semi-définie positive.

On dispose seulement de quelques entrées pour $(i,j)\in\Omega$ : $\quad\forall i,j\,\in\Omega,\quad A^i_j=\overline{e}^iA\vec{e}_j$.

Cette fois on a donc : $\mathcal{C}_1 = \mathcal{S}_n^+(\mathbb{R})$ et $\mathcal{C}_2 = \left\{X \in \mathcal{M}_n(\mathbb{R}) \mbox{ t.q. } X^i_j\overset{\Delta}{=}\overline{e}^iX\vec{e}_j=A^i_j \right\}$.

**Question 1** : justifier que ces parties sont convexes non vides fermées.

**Question 2 :** On choisit de munir $\mathcal{M}_n(\mathbb{R})$ du produit scalaire $<X,Y>=tr(XY^T)$. On a alors $d(\Delta,\mathcal{C}_i)=\Vert \Delta - \Pi_{\mathcal{C}_i}(\Delta)\Vert_F$, avec $\Vert \Vert_F$ la norme de Frobenius, et $\Pi_{\mathcal{C}_i}(\Delta)$ le projeté de $\Delta$ sur $\mathcal{C}_i$. Donner l'expression analytique des $\Pi_{\mathcal{C}_i}(\Delta)$.

**Réponse**

Soit $X\in\mathcal{M}_n(\mathbb{R})$. $\tilde{X}:=\displaystyle\frac{X+X^T}{2}\in\mathcal{S}_n(\mathbb{R})$, on note $\tilde{X}=P\times\textrm{diag}(\{\lambda_i\})\times P^T$ alors 
$$\Pi_{\mathcal{C}_1}(X)=\Pi_{\mathcal{S}_n^+(\mathbb{R})}(X)=P\times\textrm{diag}(\{\max\{0, \lambda_i\}\})\times P^T$$

On obtient la projection sur $\mathcal{C}_1$ avec KKT :
$$\begin{align}
\Pi_{\mathcal{C}_1}(X) = X-\sum_{(i,j)\in\Omega}\left(\overline{e}^i(X-1)\vec{e}_j\right)\vec{e}_i\overline{e}^j
\end{align}$$

### Définition du problème

On se donne une matrice B symétrique semi-définie positive, dont on extrait certaines valeurs.

In [8]:
n = 100;
B = randn(n,n);
B = (B+transpose(B))/2

100×100 Array{Float64,2}:
 -0.788052   -0.184059   -0.234741  …  -0.306303   -0.616941   -1.75875
 -0.184059   -0.60766    -0.471585      0.41057     1.4323      0.150837
 -0.234741   -0.471585   -1.39094      -0.813912   -0.601935   -0.975607
 -0.581199   -0.905466   -1.74793       0.53645    -0.948484   -0.330959
 -0.626911   -1.0003      0.474329     -0.457739    0.460644   -0.34791
  0.137619   -1.53562     0.85053   …  -0.343632   -0.901751   -0.837786
 -0.688471    0.86537    -0.920525     -1.53142     0.740828    0.412441
  0.167414   -0.055306   -0.357986      0.849293   -0.695142   -0.119414
 -0.753199   -0.554335    1.21483      -0.890449    0.190182    0.828788
  1.26319     0.630042   -0.870081      0.0174326  -0.236507    0.210054
  0.208895    0.285814   -0.975251  …   1.05085     0.0258478   0.372676
  0.348308    0.0964197  -0.103534      0.285342   -0.286592    0.428697
 -0.479123   -1.51058    -0.251905      0.880848    0.61854     0.293244
  ⋮                        

In [9]:
rand(1:100,10,2)

10×2 Array{Int64,2}:
 25  58
 63  51
 20  34
 82   7
 83  35
 64  79
  2  80
 38  18
 46  34
 98  47

In [10]:
using StatsBase

In [11]:
hcat(sample(1:10,5), sample(1:10,5))

5×2 Array{Int64,2}:
 5   1
 3   2
 3  10
 8   9
 8   6

In [12]:
n = 100;
A = Symmetric(randn(n,n));
#import Pkg;
#Pkg.add("Random")
nb_known_entries = 30
known_indices = hcat(sample(1:n,nb_known_entries), sample(1:n,nb_known_entries))

30×2 Array{Int64,2}:
 11  43
  2  85
 45  19
 67  44
  9  13
 74  87
 68  21
 72  73
  5  23
 65  21
 80   1
 11  71
 50  57
  ⋮  
  6  27
 98  83
 51  50
 95  85
 57  71
 49  74
 11  26
 35  43
 32  46
  7  86
 18  78
 52  62

In [13]:
function h(X,A,known_indices)
    return sum(X[known_indices]-A[known_indices])
end

function Pi1(X)
    Sym = pi1(X)
    eigen = eigen(Sym)
    P = eigen.vectors
    Diag = Diagonal(eigen.values)

LoadError: syntax: incomplete: "function" at In[13]:5 requires end